export const TASK_SEQUENCE = ["auth", "transfer", "bank", "telemetry"] as const;
export type TaskStep = (typeof TASK_SEQUENCE)[number];

export const NIGERIAN_BANKS = [
  "Access Bank",
  "Citibank Nigeria",
  "Ecobank Nigeria",
  "Fidelity Bank",
  "First Bank of Nigeria",
  "First City Monument Bank (FCMB)",
  "Globus Bank",
  "Guaranty Trust Bank (GTBank)",
  "Heritage Bank",
  "Keystone Bank",
  "Polaris Bank",
  "Premium Trust Bank",
  "Providus Bank",
  "Stanbic IBTC Bank",
  "Standard Chartered Bank",
  "Sterling Bank",
  "SunTrust Bank",
  "Union Bank of Nigeria",
  "United Bank for Africa (UBA)",
  "Unity Bank",
  "Wema Bank",
  "Zenith Bank",
  "Jaiz Bank",
  "Lotus Bank",
  "Parallex Bank",
  "Titan Trust Bank",
  "Signature Bank",
  "Optimus Bank",
];

export const EXPORT_HEADERS = [
  "session_id",
  "event_index",
  "task_completion_speed",
  "Inter_event_idle_duration",
  "Typing actions",
  "Text fixes",
  "Login attempts",
  "Login problems",
  "Review checks",
  "Transfers completed",
  "Swipe incomplete",
  "Swipe completes",
  "swipe curve",
  "Navigation taps",
  "Motion checks",
  "Orientation checks",
  "Average button pressure",
  "Neuromuscular Entropy",
  "Distribution jitter",
  "Background checks",
  "Average key hold (ms)",
  "Average key gap (ms)",
  "Scroll irregularity",
  "Tap-to-vibration correlation",
  "Touch area deformation",
  "Touch area deformation ratio",
  "Multi-touch anomalies",
  "Paste detected",
  "Pasted characters",
  "Autofill detected",
  "Autofilled characters",
  "Cut events",
  "Copy events",
  "GPS lat",
  "GPS lng",
  "GPS accuracy",
  "Battery level",
  "Battery charging",
  "Screen brightness",
  "Device model",
  "OS version",
  "Platform",
  "Network type",
  "Session started at",
  "Session ended at",
  "Session duration (ms)",
  "Avg touch hold (ms)",
  "Touch hold variance",
  "Avg touch precision (px)",
  "Touch precision variance",
  "Avg field dwell (ms)",
  "Total field focus (ms)",
  "Field revisits",
  "Password unmask count",
  "Backspace bursts",
  "Single backspaces",
  "Backspace burst ratio",
  "Digraph pairs",
  "Digraph timing variance",
  "Digraph timing mean (ms)",
  "is_human",
];
