export const africanLanguages: string[] = [
  // Major/national languages
  "Swahili", "Amharic", "Hausa", "Yoruba", "Igbo", "Oromo", "Somali",
  "Zulu", "Shona", "Arabic", "French", "English", "Portuguese",
  "Afrikaans", "Malagasy", "Lingala", "Kinyarwanda", "Kirundi",
  "Wolof", "Fula", "Tigrinya", "Bambara", "Tswana", "Sotho",
  "Northern Sotho", "Tsonga", "Swati", "Venda", "Ndebele",
  "Xhosa", "Kikuyu", "Luganda", "Akan", "Twi", "Fante",
  "Ewe", "Ga", "Dagbani", "Kasem", "Kabiye", "Moore", "Dinka",
  "Nuer", "Bari", "Acholi", "Luo", "Maasai", "Kalenjin", "Turkana",
  "Samburu", "Pokot", "Teso", "Lango", "Runyankole", "Rukiga",
  "Lugbara", "Alur", "Madi", "Kakwa", "Bemba", "Nyanja", "Chewa",
  "Tumbuka", "Shangaan", "Tsonga", "Ndau", "Nambya", "Chikunda",
  "Nsenga", "Sena", "Yao", "Makonde", "Makua", "Sango", "Kongo",
  "Luba", "Lunda", "Luvale", "Bemba", "Kaonde", "Nyanja",
  "Tonga", "Ila", "Lenje", "Soli", "Chewa", "Ngoni", "Manda",
  "Kwere", " Doe", "Zaramo", "Luguru", "Kami", "Kutu", "Sagala",
  "Taveta", "Taita", "Mijikenda", "Pokomo", "Orma", "Borana",
  "Gabbra", "Rendille", "Dasenech", "Burji", "Konso", "Dirasha",
  "Gamo", "Gofa", "Wolaytta", "Sidamo", "Hadiyya", "Kambaata",
  "Gurage", "Harari", "Argobba", "Zay", "Afar", "Saho", "Beja",
  "Hadiyya", "Kafa", "Sheko", "Majang", "Anuak", "Nuer", "Shilluk",
  "Anywa", "Berta", "Gumuz", "Awngi", "Qimant", "Chaha", "Inor",
  "Mesmes", "Soddo", "Goggot", "Masqan", "Guraferda", "Yemsa",
  "Basketo", "Dime", "Hammer", "Aari", "Dhaasanac", "Kara",
  "Mursi", "Suri", "Nyangatom", "Toposa", "Turkana", "Maasai",
  // Berber/Amazigh
  "Tamazight", "Tachelhit", "Tarifit", "Kabyle", "Chaoui",
  "Tamahaq", "Ghomara", "Nafusi", "Siwi", "Zenaga",
  // West African
  "Bassa", "Kpelle", "Grebo", "Krahn", "Gio", "Mano", "Loma",
  "Belle", "Gbandi", "Mende", "Temne", "Limba", "Kuranko", "Yalunka",
  "Susu", "Dyula", "Soninke", "Bambara", "Khassonke", "Maninka",
  "Fula", "Pulaar", "Tukulor", "Serer", "Wolof", "Jola", "Mandjak",
  "Mankanya", "Papel", "Balanta", "Manjaco", "Bijago", "Cape Verdean Creole",
  "Kabuverdianu", "Guinea-Bissau Creole", "Krio", "Temne", "Loko",
  "Songo", "Kimbundu", "Umbundu", "Kikongo", "Chokwe", "Ngangela",
  "Luvale", "Mbunda", "Luchazi", "Nyemba", "Oshiwambo", "Kwangali",
  "Mbukushu", "Gciriku", "Yeyi", "Subiya", "Totela", "Fwe",
  "Shiyeyi", "Thimbukushu", "Rumanyo", "Diriku", "Mbogedu",
  // Nigerian minority languages
  "Tiv", "Idoma", "Igala", "Nupe", "Gbagyi", "Ebira", "Jukun",
  "Fulfulde", "Kanuri", "Babur", "Bura", "Margi", "Higi", "Kilba",
  "Bachama", "Mbula", "Longuda", "Daba", "Gude", "Gbwata", "Fali",
  "Gbaya", "Zul", "Gude", "Bata", "Bacama", "Kamwe", "Samba",
  "Daka", "Samba Daka", "Sha", "Kugbo", "Waja", "Tangle", "Bole",
  "Ngamo", "Karekare", "Miship", "Ngas", "Mwaghavul", "Goemai",
  "Tal", "Pyapun", "Miship", "Dirim", "Kwonja", "Mama", "Kumba",
  "Kporo", "Bokkos", "Kulere", "Richa", "Ibwen", "Fyer", "Sura",
  "Mangas", "Bu", "Kudu-Camo", "Kono", "Gbantu", "Iten", "Oegworok",
  "Izere", "Bijim", "Lijili", "Luri", "Siketi", "Ningye", "Kadung",
  "Kasem", "Chumburung", "Larteh", "Akyem", "Kwahu", "Akuapem",
  "Abron", "Selee", "Sekpele", "Siwu", "Logba", "Avatime",
  "Nyangbo", "Tafi", "Adangbe", "Adele", "Nkonya", "Ede Nago",
  "Ifè", "Anii", "Aja", "Waci", "Foodo", "Waama", "Yobe",
  "Dendi", "Bariba", "Yom", "Lukpa", "Kali", "Tchumbuli", "Boko",
  "Bokobaru", "Shanga", "Busa", "Bokyi", "Ejagham", "Nkim",
  "Nkum", "Oron", "Obolo", "Ibeno", "Eket", "Ibibio", "Efik",
  "Annang", "Oro", "Ekid", "Iko", "Andoni", "Ogoni", "Khana",
  "Gokana", "Eleme", "Tai", "Ijaw", "Izon", "Kalabari", "Okrika",
  "Nembe", "Ogbia", "Biseni", "Oyakame", "Defaka", "Nkoroo",
  "Igbani", "Akpane", "Ogbogolo", "Engenni", "Zaramo", "Kwere",
  "Doe", "Kami", "Kutu", "Sagala", "Taveta", "Taita", "Mijikenda",
  // Creoles
  "Krio", "Nigerian Pidgin", "Cameroonian Pidgin", "Sranan Tongo",
  "Seychellois Creole", "Mauritian Creole",
  // Central/East African minority
  "Hadza", "Sandawe", "Iraqw", "Gorowa", "Alagwa", "Burunge",
  "Ma'a", "Bungu", "Kimbu", "Pimbwe", "Fipa", "Mambwe", "Lungu",
  "Namwanga", "Nyamwezi", "Sukuma", "Nyaturu", "Rangi", "Gogo",
  "Hehe", "Bena", "Pangwa", "Kinga", "Wanji", "Kisi", "Mpoto",
  "Nyiha", "Lambya", "Ndali", "Nyakyusa", "Safwa", "Malila",
  "Sangu", "Wanji", "Vwanji", "Bena", "Pogolo", "Ndamba", "Mbunga",
  "Bwela", "Lala", "Bisa", "Lala-Bisa", "Ushi", "Lala", "Ambo",
  "Lala", "Swaka", "Lala", "Kaonde", "Lunda", "Luvale", "Chokwe",
  "Mbunda", "Luchazi", "Ngangela", "Nyemba", "Lucazi", "Mbunda",
  "Rukwa", "Pimbwe", "Fipa", "Mambwe", "Lungu", "Safwa", "Malila",
  "Sangu", "Wanji", "Kinga", "Pangwa", "Bena", "Hehe", "Gogo",
  "Rangi", "Nyaturu", "Sukuma", "Nyamwezi", "Kimbu", "Pimbwe",
  // Additional widely-spoken
  "Spanish", "German", "Italian", "Hindi", "Urdu", "Gujarati",
  "Mandarin Chinese", "Cantonese",
];
